services:
  namenode:
    image: apache/hadoop:3.4.1
    container_name: namenode
    hostname: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - ./hadoop_namenode:/opt/hadoop/data/namenode
      - ./hadoop_config:/opt/hadoop/etc/hadoop
      - ./start-hdfs.sh:/start-hdfs.sh
    environment:
      - CLUSTER_NAME=big-data-programming-coursework
      - HADOOP_OPTS=-Dhadoop.security.logger=INFO,RFAS
      - HADOOP_HOME=/opt/hadoop
      - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre
    env_file:
      - ./hadoop.env
    command: [ "/bin/bash", "/start-hdfs.sh" ]
    healthcheck:
      test: ["CMD-SHELL", "hdfs dfsadmin -report | grep 'Live datanodes'"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - hadoop-network

  datanode:
    image: apache/hadoop:3.4.1
    container_name: datanode
    hostname: datanode
    user: root
    depends_on:
      - namenode
    volumes:
      - ./hadoop_datanode:/opt/hadoop/data/datanode
      - ./hadoop_config:/opt/hadoop/etc/hadoop
      - ./init-datanode.sh:/init-datanode.sh
    environment:
      - CLUSTER_NAME=big-data-programming-coursework
      - HADOOP_OPTS=-Dhadoop.security.logger=INFO,RFAS
      - HADOOP_HOME=/opt/hadoop
      - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre
    env_file:
      - ./hadoop.env
    command: [ "/bin/bash", "/init-datanode.sh" ]
    networks:
      - hadoop-network

  resourcemanager:
    image: apache/hadoop:3.4.1
    container_name: resourcemanager
    hostname: resourcemanager
    ports:
      - "8088:8088"
    depends_on:
      - namenode
      - datanode
    volumes:
      - ./hadoop_config:/opt/hadoop/etc/hadoop
    environment:
      - CLUSTER_NAME=big-data-programming-coursework
      - HADOOP_OPTS=-Dhadoop.security.logger=INFO,RFAS
      - HADOOP_HOME=/opt/hadoop
      - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre
    env_file:
      - ./hadoop.env
    command: ["/bin/bash", "-c", "/opt/hadoop/bin/yarn resourcemanager"]
    networks:
      - hadoop-network

  nodemanager:
    image: apache/hadoop:3.4.1
    container_name: nodemanager
    hostname: nodemanager
    depends_on:
      - namenode
      - resourcemanager
    volumes:
      - ./hadoop_config:/opt/hadoop/etc/hadoop
    environment:
      - CLUSTER_NAME=big-data-programming-coursework
      - HADOOP_OPTS=-Dhadoop.security.logger=INFO,RFAS
      - HADOOP_HOME=/opt/hadoop
      - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre
    env_file:
      - ./hadoop.env
    command: ["/bin/bash", "-c", "/opt/hadoop/bin/yarn nodemanager"]
    networks:
      - hadoop-network

networks:
  hadoop-network:
    driver: bridge
