services:
  namenode:
    image: apache/hadoop:3.4.1
    container_name: namenode
    hostname: namenode
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - ./hadoop_namenode:/opt/hadoop/data/namenode
      - ./hadoop_config:/opt/hadoop/etc/hadoop
      - ./init-scripts/start-hdfs.sh:/start-hdfs.sh
    environment:
      - CLUSTER_NAME=big-data-programming-coursework
      - HADOOP_OPTS=-Dhadoop.security.logger=INFO,RFAS
      - HADOOP_HOME=/opt/hadoop
      - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
    env_file:
      - ./hadoop.env
    command: [ "/bin/bash", "/start-hdfs.sh" ]
    healthcheck:
      test: [ "CMD-SHELL", "hdfs dfsadmin -report | grep 'Live datanodes'" ]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - hadoop-network

  datanode-1:
    image: apache/hadoop:3.4.1
    container_name: datanode-1
    hostname: datanode
    user: root
    depends_on:
      - namenode
    volumes:
      - ./hadoop_datanode_1:/opt/hadoop/data/datanode
      - ./hadoop_config:/opt/hadoop/etc/hadoop
      - ./init-scripts/init-datanode.sh:/init-datanode.sh
    environment:
      - CLUSTER_NAME=big-data-programming-coursework
      - HADOOP_OPTS=-Dhadoop.security.logger=INFO,RFAS
      - HADOOP_HOME=/opt/hadoop
      - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
    env_file:
      - ./hadoop.env
    command: [ "/bin/bash", "/init-datanode.sh" ]
    networks:
      - hadoop-network

  datanode-2:
    image: apache/hadoop:3.4.1
    container_name: datanode-2
    hostname: datanode
    user: root
    depends_on:
      - namenode
    volumes:
      - ./hadoop_datanode_2:/opt/hadoop/data/datanode
      - ./hadoop_config:/opt/hadoop/etc/hadoop
      - ./init-scripts/init-datanode.sh:/init-datanode.sh
    environment:
      - CLUSTER_NAME=big-data-programming-coursework
      - HADOOP_OPTS=-Dhadoop.security.logger=INFO,RFAS
      - HADOOP_HOME=/opt/hadoop
      - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
    env_file:
      - ./hadoop.env
    command: [ "/bin/bash", "/init-datanode.sh" ]
    networks:
      - hadoop-network


  resourcemanager:
    image: apache/hadoop:3.4.1
    container_name: resourcemanager
    hostname: resourcemanager
    ports:
      - "8088:8088"
    depends_on:
      - namenode
      - datanode-1
      - datanode-2
    volumes:
      - ./hadoop_config:/opt/hadoop/etc/hadoop
    environment:
      - CLUSTER_NAME=big-data-programming-coursework
      - HADOOP_OPTS=-Dhadoop.security.logger=INFO,RFAS
      - HADOOP_HOME=/opt/hadoop
      - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
    env_file:
      - ./hadoop.env
    command: [ "/bin/bash", "-c", "/opt/hadoop/bin/yarn resourcemanager" ]
    networks:
      - hadoop-network

  nodemanager:
    image: apache/hadoop:3.4.1
    container_name: nodemanager
    hostname: nodemanager
    depends_on:
      - namenode
      - resourcemanager
    volumes:
      - ./hadoop_config:/opt/hadoop/etc/hadoop
    environment:
      - CLUSTER_NAME=big-data-programming-coursework
      - HADOOP_OPTS=-Dhadoop.security.logger=INFO,RFAS
      - HADOOP_HOME=/opt/hadoop
      - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre
      - HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
    env_file:
      - ./hadoop.env
    command: [ "/bin/bash", "-c", "/opt/hadoop/bin/yarn nodemanager" ]
    networks:
      - hadoop-network

  hive-metastore-db:
    image: postgres:15.15-alpine3.22
    container_name: hive-metastore-db
    environment:
      POSTGRES_DB: metastore_db
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: Test@123
    volumes:
      - hive-db-data:/var/lib/postgresql/data
    networks:
      - hadoop-network

  hive-metastore:
    image: apache/hive:standalone-metastore-4.2.0
    container_name: hive-metastore
    depends_on:
      - hive-metastore-db
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      SERVICE_OPTS: "-Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://hive-metastore-db:5432/metastore_db -Djavax.jdo.option.ConnectionUserName=hive -Djavax.jdo.option.ConnectionPassword=Test@123"
      HIVE_SITE_CONF_fs_defaultFS: "hdfs://namenode:9000"
    volumes:
      - ./drivers/postgresql-42.7.3.jar:/opt/hive/lib/postgresql-42.7.3.jar
    networks:
      - hadoop-network

  hive-server:
    image: apache/hive:4.2.0
    container_name: hive-server
    depends_on:
      - hive-metastore
    ports:
      - "10000:10000"
      - "10002:10002"
    environment:
      SERVICE_NAME: hiveserver2
      HIVE_SITE_CONF_hive_metastore_uris: "thrift://hive-metastore:9083"
      HIVE_SITE_CONF_fs_defaultFS: "hdfs://namenode:9000"
    networks:
      - hadoop-network

  spark-master:
    image: apache/spark:4.0.1
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_WORKLOAD=master
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - SPARK_NO_DAEMONIZE=true
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    depends_on:
      - namenode
    networks:
      - hadoop-network

  spark-worker:
    image: apache/spark:4.0.1
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=4g
      - SPARK_NO_DAEMONIZE=true
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    networks:
      - hadoop-network
    deploy:
      replicas: 1

volumes:
  hive-db-data:

networks:
  hadoop-network:
    driver: bridge
